version: "3"
services:
  market-client-v2:
    container_name: market-client-v2
    build:
      context: .
      dockerfile: Dockerfile
    platform: "linux/amd64"
    restart: unless-stopped
    env_file: .env
    environment:
      NEXT_PUBLIC_BASE_URL: http://localhost:1337/api
      COOKIE_PASSWORD: complex_password_at_least_32_characters_long
      COOKIE_NAME: myapp_cookiename
    ports:
      - "8000:8000"
